# Configures when (if at all) codecov will create GitHub comments on a Pull Request
# and what should be included in the comment.
comment: false

#comment:
#  layout: "header, diff, changes, uncovered, tree"
#  behavior: default
