---
http_interactions:
- request:
    method: post
    uri: "<tutor_specs_instance_url>/services/data/v37.0/sobjects/Lead"
    body:
      encoding: UTF-8
      string: '{"FirstName":"Keyshawn","LastName":"Harvey","Subject__c":"","Company":"JP
        University","Website":"http://www.rice.edu","Email":"f@f.com","LeadSource":"OSC
        Faculty","Newsletter__c":true,"Newsletter_Opt_In__c":true,"Adoption_Status__c":"Confirmed
        Adoption Won","Number_of_Students__c":0,"OS_Accounts_ID__c":3,"Application_Source__c":""}'
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/json
      Authorization:
      - OAuth <tutor_specs_oauth_token>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 201
      message: Created
    headers:
      Connection:
      - close
      Date:
      - Wed, 27 Dec 2017 15:05:25 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Content-Security-Policy:
      - upgrade-insecure-requests
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=e-b6graSQJaOD0S8UPVy3w;Path=/;Domain=.salesforce.com;Expires=Sun,
        25-Feb-2018 15:05:25 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Sforce-Limit-Info:
      - api-usage=7/48000
      Location:
      - "/services/data/v37.0/sobjects/Lead/00QW0000006J2QOMA0"
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
    body:
      encoding: ASCII-8BIT
      string: '{"id":"00QW0000006J2QOMA0","success":true,"errors":[]}'
    http_version: 
  recorded_at: Wed, 27 Dec 2017 15:05:26 GMT
- request:
    method: get
    uri: "<tutor_specs_instance_url>/services/data/v37.0/query?q=SELECT%20Id,%20Name,%20FirstName,%20LastName,%20Salutation,%20Subject__c,%20Company,%20Phone,%20Website,%20Status,%20Email,%20LeadSource,%20Newsletter__c,%20Newsletter_Opt_In__c,%20Adoption_Status__c,%20Number_of_Students__c,%20OS_Accounts_ID__c,%20accounts_uuid_c__c,%20Application_Source__c%20FROM%20Lead%20WHERE%20(Id%20=%20%2700QW0000006J2QOMA0%27)%20LIMIT%201"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <tutor_specs_oauth_token>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Connection:
      - close
      Date:
      - Wed, 27 Dec 2017 15:05:26 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Content-Security-Policy:
      - upgrade-insecure-requests
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=tcDc6ur0S9WACeOUU6TEcA;Path=/;Domain=.salesforce.com;Expires=Sun,
        25-Feb-2018 15:05:26 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Sforce-Limit-Info:
      - api-usage=8/48000
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
    body:
      encoding: ASCII-8BIT
      string: '{"totalSize":1,"done":true,"records":[{"attributes":{"type":"Lead","url":"/services/data/v37.0/sobjects/Lead/00QW0000006J2QOMA0"},"Id":"00QW0000006J2QOMA0","Name":"Keyshawn
        Harvey","FirstName":"Keyshawn","LastName":"Harvey","Salutation":null,"Subject__c":null,"Company":"JP
        University","Phone":null,"Website":"http://www.rice.edu","Status":"Needs School","Email":"f@f.com","LeadSource":"OSC
        Faculty","Newsletter__c":true,"Newsletter_Opt_In__c":true,"Adoption_Status__c":"Confirmed
        Adoption Won","Number_of_Students__c":30.0,"OS_Accounts_ID__c":"3","accounts_uuid_c__c":null,"Application_Source__c":null}]}'
    http_version: 
  recorded_at: Wed, 27 Dec 2017 15:05:26 GMT
recorded_with: VCR 3.0.3
