# config/app.yml for rails-settings-cached
defaults: &defaults
  push_salesforce_lead_enabled: false
  subjects:
    hs_physics:
      title: High School Physics
      sf: HS Physics
    college_physics:
      title: College Physics
      sf: College Physics (Algebra)
    ap_biology:
      title: Biology for AP® Courses
      sf: AP Bio
    concepts_biology:
      title: Concepts of Biology
      sf: Concepts of Bio (non-majors)
    college_biology:
      title: College Biology
      sf: Biology w Courseware
    principles_economics:
      title: Principles of Economics
      sf: Economics
    macro_economics:
      title: Macro Economics
      sf: Macro Econ
    micro_economics:
      title: Micro Economics
      sf: Micro Econ
    intro_sociology:
      title: Introduction to Sociology
      sf: Introduction to Sociology
    anatomy_physiology:
      title: Anatomy & Physiology
      sf: Anatomy & Physiology

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
