# config/app.yml for rails-settings-cached
defaults: &defaults
  push_salesforce_lead_enabled: false
  subjects:
    ap_bio:
      title: AP Bio
      sf: AP Bio
    ap_macro_econ:
      title: AP Macro Econ
      sf: AP Macro Econ
    ap_micro_econ:
      title: AP Micro Econ
      sf: AP Micro Econ
    ap_physics:
      title: AP Physics
      sf: AP Physics
    accounting:
      title: Accounting
      sf: Accounting
    algebra_and_trigonometry:
      title: Algebra and Trigonometry
      sf: Algebra and Trigonometry
    american_government:
      title: American Government
      sf: American Government
    anatomy_physiology:
      title: Anatomy & Physiology
      sf: Anatomy & Physiology
    astronomy:
      title: Astronomy
      sf: Astronomy
    basic_college_math:
      title: Basic College Math
      sf: Basic College Math
    biology:
      title: Biology
      sf: Biology
    biology_w_courseware:
      title: Biology w Courseware
      sf: Biology w Courseware
    calculus:
      title: Calculus
      sf: Calculus
    chem_atoms_first:
      title: 'Chemistry: Atoms First'
      sf: 'Chem: Atoms First'
    chemistry:
      title: Chemistry
      sf: Chemistry
    college_algebra:
      title: College Algebra
      sf: College Algebra
    college_physics_algebra:
      title: 'College Physics (Algebra)'
      sf: 'College Physics (Algebra)'
    concepts_of_bio_non_majors:
      title: 'Concepts of Bio (non-majors)'
      sf: 'Concepts of Bio (non-majors)'
    economics:
      title: Economics
      sf: Economics
    elementary_algebra:
      title: Elementary Algebra
      sf: Elementary Algebra
    finite_algebra:
      title: Finite Algebra
      sf: Finite Algebra
    hs_physics:
      title: HS Physics
      sf: HS Physics
    hs_statistics:
      title: HS Statistics
      sf: HS Statistics
    intermediate_algebra:
      title: Intermediate Algebra
      sf: Intermediate Algebra
    introduction_to_business:
      title: Introduction to Business
      sf: Introduction to Business
    introduction_to_sociology:
      title: Introduction to Sociology
      sf: Introduction to Sociology
    introduction_to_spanish:
      title: Introduction to Spanish
      sf: Introduction to Spanish
    introductory_statistics:
      title: Introductory Statistics
      sf: Introductory Statistics
    macro_econ:
      title: Macro Econ
      sf: Macro Econ
    management:
      title: Management
      sf: Management
    micro_econ:
      title: Micro Econ
      sf: Micro Econ
    microbiology:
      title: Microbiology
      sf: Microbiology
    other:
      title: Other
      sf: Other
    physics_w_courseware:
      title: Physics w Courseware
      sf: Physics w Courseware
    pre_algebra:
      title: PreAlgebra
      sf: PreAlgebra
    precalc:
      title: Precalc
      sf: Precalc
    psychology:
      title: Psychology
      sf: Psychology
    sociology_w_courseware:
      title: Sociology w Courseware
      sf: Sociology w Courseware
    us_history:
      title: US History
      sf: US History
    university_physics:
      title: University Physics
      sf: University Physics

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
