# config/app.yml for rails-settings-cached
defaults: &defaults
  push_salesforce_lead_enabled: false
  subjects:
    hs_physics:
      title: High School Physics
      sf: HS Physics
    college_physics:
      title: College Physics
      sf: Phys
    ap_biology:
      title: Biology for AP® Courses
      sf: APBio
    concepts_biology:
      title: Concepts of Biology
      sf: Concepts Bio
    college_biology:
      title: College Biology
      sf: College Bio
    principles_economics:
      title: Principles of Economics
      sf: Princ Econ
    macro_economics:
      title: Macro Economics
      sf: Macroeconomics
    micro_economics:
      title: Micro Economics
      sf: Macroeconomics
    intro_sociology:
      title: Introduction to Sociology
      sf: Intro Soc
    anatomy_physiology:
      title: Anatomy & Physiology
      sf: 'AnP'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
