---
http_interactions:
- request:
    method: post
    uri: "<salesforce_instance_url>/services/data/v37.0/sobjects/Lead"
    body:
      encoding: UTF-8
      string: '{"FirstName":"Nisha","LastName":"Pfannerstill","Subject__c":"","Company":"JP
        University","Website":"http://www.rice.edu","Email":"f@f.com","LeadSource":"OSC
        Faculty","Newsletter__c":true,"Newsletter_Opt_In__c":true,"Adoption_Status__c":"Confirmed
        Adoption Won","Number_of_Students__c":0,"OS_Accounts_ID__c":2,"Application_Source__c":"Accounts","Role__c":"instructor"}'
    headers:
      User-Agent:
      - Faraday v0.17.3
      Content-Type:
      - application/json
      Authorization:
      - OAuth <salesforce_access_token>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Fri, 06 Nov 2020 15:56:29 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://a.forcesslreports.com/hpkp-report/00D7X000000Gyi2m";
      Expect-Ct:
      - max-age=86400, report-uri="https://a.forcesslreports.com/Expect-CT-report/00D7X000000Gyi2m"
      X-Robots-Tag:
      - none
      X-B3-Traceid:
      - 81be2f1541efb8f5
      X-B3-Spanid:
      - 81be2f1541efb8f5
      X-B3-Sampled:
      - '0'
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=ohYzNyBIEeuKtolksxeoig; domain=.salesforce.com; path=/; expires=Sat,
        06-Nov-2021 15:56:29 GMT; Max-Age=31536000
      Sforce-Limit-Info:
      - api-usage=1577/5000000
      Location:
      - "/services/data/v37.0/sobjects/Lead/00Q7X000006F9c2UAC"
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"id":"00Q7X000006F9c2UAC","success":true,"errors":[]}'
    http_version:
  recorded_at: Fri, 06 Nov 2020 15:56:31 GMT
- request:
    method: get
    uri: "<salesforce_instance_url>/services/data/v37.0/query?q=SELECT%20Id,%20Name,%20FirstName,%20LastName,%20Salutation,%20Subject__c,%20Company,%20Phone,%20Website,%20Status,%20Email,%20LeadSource,%20Newsletter__c,%20Newsletter_Opt_In__c,%20Adoption_Status__c,%20Number_of_Students__c,%20OS_Accounts_ID__c,%20accounts_uuid_c__c,%20Application_Source__c,%20Role__c,%20other_role_name__c,%20who_chooses_books__c,%20FV_Status__c,%20FV_Final__c,%20Needs_CS_Review__c,%20BRI_Marketing__c,%20Title_1_school__c%20FROM%20Lead%20WHERE%20(Id%20=%20%2700Q7X000006F9c2UAC%27)%20LIMIT%201"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.17.3
      Authorization:
      - OAuth <salesforce_access_token>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 06 Nov 2020 15:56:31 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://a.forcesslreports.com/hpkp-report/00D7X000000Gyi2m";
      Expect-Ct:
      - max-age=86400, report-uri="https://a.forcesslreports.com/Expect-CT-report/00D7X000000Gyi2m"
      X-Robots-Tag:
      - none
      X-B3-Traceid:
      - 7c9e23f99a8b1d53
      X-B3-Spanid:
      - 7c9e23f99a8b1d53
      X-B3-Sampled:
      - '0'
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=o34AiSBIEeuf8-ED9Ie_2Q; domain=.salesforce.com; path=/; expires=Sat,
        06-Nov-2021 15:56:31 GMT; Max-Age=31536000
      Sforce-Limit-Info:
      - api-usage=1576/5000000
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"totalSize":1,"done":true,"records":[{"attributes":{"type":"Lead","url":"/services/data/v37.0/sobjects/Lead/00Q7X000006F9c2UAC"},"Id":"00Q7X000006F9c2UAC","Name":"Nisha
        Pfannerstill","FirstName":"Nisha","LastName":"Pfannerstill","Salutation":null,"Subject__c":null,"Company":"JP
        University","Phone":null,"Website":"http://www.rice.edu","Status":"Converted","Email":"f@f.com","LeadSource":"OSC
        Faculty","Newsletter__c":true,"Newsletter_Opt_In__c":true,"Adoption_Status__c":"Confirmed
        Adoption Won","Number_of_Students__c":30.0,"OS_Accounts_ID__c":"2","accounts_uuid_c__c":null,"Application_Source__c":"Accounts","Role__c":"Faculty","other_role_name__c":null,"who_chooses_books__c":null,"FV_Status__c":null,"FV_Final__c":false,"Needs_CS_Review__c":false,"BRI_Marketing__c":false,"Title_1_school__c":false}]}'
    http_version:
  recorded_at: Fri, 06 Nov 2020 15:56:31 GMT
recorded_with: VCR 3.0.3
