---
http_interactions:
- request:
    method: post
    uri: "<salesforce_instance_url_lower>/services/data/v37.0/sobjects/Lead"
    body:
      encoding: UTF-8
      string: '{"FirstName":"Lavern","LastName":"Price","Subject__c":"","Company":"JP
        University","Website":"http://www.rice.edu","Email":"f@f.com","LeadSource":"OSC
        Faculty","Newsletter__c":true,"Newsletter_Opt_In__c":true,"Adoption_Status__c":"Confirmed
        Adoption Won","Number_of_Students__c":0,"OS_Accounts_ID__c":3,"Application_Source__c":"Accounts","Role__c":"instructor"}'
    headers:
      User-Agent:
      - Faraday v0.15.4
      Content-Type:
      - application/json
      Authorization:
      - OAuth <salesforce_access_token>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Wed, 04 Dec 2019 01:47:50 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://a.forcesslreports.com/hpkp-report/00DR0000001zq0Zm";
      Expect-Ct:
      - max-age=86400, report-uri="https://a.forcesslreports.com/Expect-CT-report/00DR0000001zq0Zm"
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=FGUVthY4EeqVngGbOB6r8Q;Path=/;Domain=.salesforce.com;Expires=Sun,
        02-Feb-2020 01:47:50 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Sforce-Limit-Info:
      - api-usage=2694/51000
      Location:
      - "/services/data/v37.0/sobjects/Lead/00QR000000Gov72MAB"
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"id":"00QR000000Gov72MAB","success":true,"errors":[]}'
    http_version: 
  recorded_at: Wed, 04 Dec 2019 01:47:52 GMT
- request:
    method: get
    uri: "<salesforce_instance_url_lower>/services/data/v37.0/query?q=SELECT%20Id,%20Name,%20FirstName,%20LastName,%20Salutation,%20Subject__c,%20Company,%20Phone,%20Website,%20Status,%20Email,%20LeadSource,%20Newsletter__c,%20Newsletter_Opt_In__c,%20Adoption_Status__c,%20Number_of_Students__c,%20OS_Accounts_ID__c,%20accounts_uuid_c__c,%20Application_Source__c,%20Role__c%20FROM%20Lead%20WHERE%20(Id%20=%20%2700QR000000Gov72MAB%27)%20LIMIT%201"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.15.4
      Authorization:
      - OAuth <salesforce_access_token>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 04 Dec 2019 01:47:52 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://a.forcesslreports.com/hpkp-report/00DR0000001zq0Zm";
      Expect-Ct:
      - max-age=86400, report-uri="https://a.forcesslreports.com/Expect-CT-report/00DR0000001zq0Zm"
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=FZjatRY4Eeq1eDdhRqldlA;Path=/;Domain=.salesforce.com;Expires=Sun,
        02-Feb-2020 01:47:52 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Sforce-Limit-Info:
      - api-usage=2694/51000
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"totalSize":1,"done":true,"records":[{"attributes":{"type":"Lead","url":"/services/data/v37.0/sobjects/Lead/00QR000000Gov72MAB"},"Id":"00QR000000Gov72MAB","Name":"Lavern
        Price","FirstName":"Lavern","LastName":"Price","Salutation":null,"Subject__c":null,"Company":"JP
        University","Phone":null,"Website":"http://www.rice.edu","Status":"Converted","Email":"f@f.com","LeadSource":"OSC
        Faculty","Newsletter__c":true,"Newsletter_Opt_In__c":true,"Adoption_Status__c":"Confirmed
        Adoption Won","Number_of_Students__c":30.0,"OS_Accounts_ID__c":"3","accounts_uuid_c__c":null,"Application_Source__c":"Accounts","Role__c":"Faculty"}]}'
    http_version: 
  recorded_at: Wed, 04 Dec 2019 01:47:52 GMT
recorded_with: VCR 3.0.3
